---
title: "loans"
author: "Samantha Gouveia"
date: 
output:
 html_document:
 toc: yes
 toc_depth: 4
 toc_float: yes
 fig_width: 6
 fig_caption: yes
 number_sections: yes
 theme: readable
editor_options:
 chunk_output_type: console
---


```{=html}

<style type="text/css">

/* Cascading Style Sheets (CSS) is a stylesheet language used to describe the presentation of a document written in HTML or XML. it is a simple mechanism for adding style (e.g., fonts, colors, spacing) to Web documents. */

h1.title {  /* Title - font specifications of the report title */
  font-size: 24px;
  color: DarkRed;
  text-align: center;
  font-family: "Gill Sans", sans-serif;
}
h4.author { /* Header 4 - font specifications for authors  */
  font-size: 20px;
  font-family: system-ui;
  color: DarkRed;
  text-align: center;
}
h4.date { /* Header 4 - font specifications for the date  */
  font-size: 18px;
  font-family: system-ui;
  color: DarkBlue;
text-align: center;
}
h1 { /* Header 1 - font specifications for level 1 section title  */
    font-size: 22px;
    font-family: system-ui;
    color: navy;
    text-align: left;
}
h2 { /* Header 2 - font specifications for level 2 section title */
    font-size: 20px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

h3 { /* Header 3 - font specifications of level 3 section title  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: navy;
    text-align: left;
}

h4 { /* Header 4 - font specifications of level 4 section title  */
    font-size: 18px;
    font-family: "Times New Roman", Times, serif;
    color: darkred;
    text-align: left;
}

body { background-color:white; }

.highlightme { background-color:yellow; }

p { background-color:white; }

</style>
```
##Data Introduction
The data set collected is from the small buisness association regarding different loans.
```{r}
loan01 = read.csv("https://pengdsci.github.io/datasets/SBAloan/w06-SBAnational01.csv", header = TRUE)[, -1]
loan02 = read.csv("https://pengdsci.github.io/datasets/SBAloan/w06-SBAnational02.csv", header = TRUE)[, -1]
loan03 = read.csv("https://pengdsci.github.io/datasets/SBAloan/w06-SBAnational03.csv", header = TRUE)[, -1]
loan04 = read.csv("https://pengdsci.github.io/datasets/SBAloan/w06-SBAnational04.csv", header = TRUE)[, -1]
loan05 = read.csv("https://pengdsci.github.io/datasets/SBAloan/w06-SBAnational05.csv", header = TRUE)[, -1]
loan06 = read.csv("https://pengdsci.github.io/datasets/SBAloan/w06-SBAnational06.csv", header = TRUE)[, -1]
loan07 = read.csv("https://pengdsci.github.io/datasets/SBAloan/w06-SBAnational07.csv", header = TRUE)[, -1]
loan08 = read.csv("https://pengdsci.github.io/datasets/SBAloan/w06-SBAnational08.csv", header = TRUE)[, -1]
loan09 = read.csv("https://pengdsci.github.io/datasets/SBAloan/w06-SBAnational09.csv", header = TRUE)[, -1]
loan = rbind(loan01, loan02, loan03, loan04, loan05, loan06, loan07, loan08, loan09)
# dim(bankLoan)
#names(bankLoan)
```
# MIS values 
 we will remove any missing MIS values from our data set. The main reasone for this is because the MIS_Status is our response variable. Without removing it we can not preform our analysis of the data.
```{r}
loan<- loan[complete.cases(loan$MIS_Status), ]

Once we look at the MIS values we find that 1997 observations do not have  MIS values and we will therfore remove those observations.
```

```{r}
currency_vars <- c('DisbursementGross', 'BalanceGross', 'ChgOffPrinGr', 'GrAppv', 'SBA_Appv')

for (var in currency_vars) {
  loan[, var] <- as.numeric(gsub("[\\$,]", "", loan[, var]))
}

```

```{r}
library(dplyr)
loan$LowDoc <- recode(loan$LowDoc, "sparse_category" = "combined_category")
```

```{r}

default_rate <- table(loan$MIS_Status)['CHGOFF'] / nrow(loan) * 100
print(paste("Default Rate:", default_rate, "%"))

loan$GrAppv_Category <- cut(loan$GrAppv, breaks = 5, labels = FALSE)
```


```{r}
plot(NULL, xlim = c(min(loan$SBA_Appv), max(loan$SBA_Appv)), ylim = c(0, .03),
     main = "Density Curves of SBA_Appv for 5 Sub-Populations", xlab = "SBA_Appv", ylab = "Density")

# Loop through each category and add density curve
categories <- unique(loan$GrAppv_Category)
colors <- c("red", "blue", "green", "purple", "orange")

for (i in seq_along(categories)) {
  subset_data <- loan[loan$GrAppv_Category == categories[i], ]
  
  # Plot density curve for the current category
  lines(density(subset_data$SBA_Appv), col = colors[i], lwd = 2)
}

# Add a legend
legend("topright", legend = paste("Category", categories), col = colors, lwd = 2)

```

